### ISSUE TITLE
Add an asterisk error on hello world

### ISSUE THREAD

**Issue by flenniken** [jboy/nim-pymod#12]
pymod

I'm getting the error message "Add an asterisk (`*`) after the proc name" for a simple hello world example.  What am I doing wrong?

Here is the example:

$ cat greeting.nim
import pymod
proc greet*(audience: string): string {.exportpy.} =
  return "Hello, " & audience
initPyModule("hw", greet)

I have numpy installed:

$ pip freeze
numpy==1.14.0

$ pwd
/Users/steve/code/greeting

Here is the full output:

$ python $(nimble path pymod | tail -n 1)/pmgen.py greeting.nim
Determined Python C-API includes & ldflags using command `python-config`
 - includes = ['-I/Users/steve/.virtualenvs/nim-pymod/include/python2.7', '-I/Users/steve/.virtualenvs/nim-pymod/include/python2.7']
 - ldflags = ['-L/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config', '-lpython2.7', '-ldl', '-framework', 'CoreFoundation']
Found Numpy installation at: /Users/steve/.virtualenvs/nim-pymod/lib/python2.7/site-packages/numpy
Numpy installation paths: ['/Users/steve/.virtualenvs/nim-pymod/lib/python2.7/site-packages/numpy']
Determined Numpy C-API includes
 - includes = ['-I/Users/steve/.virtualenvs/nim-pymod/lib/python2.7/site-packages/numpy/core/include']
make -f Makefile.pmgen-greeting pmgen
nim compile  --define:pmgen  --noLinking --noMain pmgengreeting_incl.nim
Hint: used config file '/usr/local/Cellar/nim/0.17.2/nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/steve/code/greeting/pmgen/nim.cfg' [Conf]
Hint: system [Processing]
Hint: pmgengreeting_incl [Processing]
Hint: macros [Processing]
Hint: astutils [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: times [Processing]
Hint: posix [Processing]
Hint: ospaths [Processing]
Hint: impls [Processing]
Hint: hashes [Processing]
Hint: docstrings [Processing]
Hint: registrytypes [Processing]
Hint: sequtils [Processing]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(29, 55) Warning: stmt is deprecated [Deprecated]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(38, 20) Warning: expr is deprecated [Deprecated]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(38, 27) Warning: stmt is deprecated [Deprecated]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(48, 26) Warning: expr is deprecated [Deprecated]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(48, 33) Warning: stmt is deprecated [Deprecated]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(51, 29) Warning: expr is deprecated [Deprecated]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(51, 36) Warning: stmt is deprecated [Deprecated]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(58, 57) Warning: expr is deprecated [Deprecated]
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(58, 65) Warning: stmt is deprecated [Deprecated]
Hint: pymod [Processing]
Hint: pyobject [Processing]
stack trace: (most recent call last)
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/includes/realmacrodefs.nim(49) exportpy
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/impls.nim(543) exportpyImpl
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/impls.nim(258) verifyProcDef
/Users/steve/code/greeting/greeting.nim(2, 39) template/generic instantiation from here
/Users/steve/.nimble/pkgs/pymod-0.1.0/pymodpkg/private/impls.nim(258, 10) Error: can't exportpy proc `greet` [/Users/steve/code/greeting/greeting.nim(2, 0)] because it isn't marked for export from the module.
Hint: Add an asterisk (`*`) after the proc name, as described here:
 http://nim-lang.org/manual.html#export-marker

      error(msg)
           ^
make: *** [pmgen] Error 1
Traceback (most recent call last):
  File "/Users/steve/.nimble/pkgs/pymod-0.1.0/pmgen.py", line 525, in <module>
    main()
  File "/Users/steve/.nimble/pkgs/pymod-0.1.0/pmgen.py", line 161, in main
    pmgen_fnames = generate_pmgen_files(nim_modfiles, pminc_basename)
  File "/Users/steve/.nimble/pkgs/pymod-0.1.0/pmgen.py", line 334, in generate_pmgen_files
    subprocess.check_call(make_command)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.pmgen-greeting', 'pmgen']' returned non-zero exit status 2
(nim-pymod) [steve@fireplace] ~/code/greeting

**Comment by apahl** [comment]
See https://github.com/jboy/nim-pymod/issues/10 .

As this project seems to be unmaintained, you should also keep an eye on https://github.com/yglukhov/python .

Kind regards,
Axel
