### ISSUE TITLE
pmgen.py error

### ISSUE THREAD

**Issue by subsetpark** [jboy/nim-pymod#7]
When attempting to run `python pmgen.py` on my nim source, I get the following error:

```
stack trace: (most recent call last)
/Users/zax/mksp/hybrid/nim-pymod/pymodpkg/private/includes/realmacrodefs.nim(49) exportpy
/Users/zax/mksp/hybrid/nim-pymod/pymodpkg/private/impls.nim(550) exportpyImpl
/Users/zax/mksp/hybrid/nim-pymod/pymodpkg/private/impls.nim(550) exportpyImpl(403) getReturnType
/Users/zax/mksp/hybrid/nim-pymod/pymodpkg/private/impls.nim(550) exportpyImpl(403) getReturnType(147) verifyBuiltinNimType
lib/core/macros.nim(380) expectKind
/Users/zax/mksp/hybrid/inner_loop.nim(20, 33) template/generic instantiation from here
lib/core/macros.nim(380, 24) Error: Expected a node of kind nnkIdent, got nnkBracketExpr
    if n.kind != k: error("Expected a node of kind " & $k & ", got " & $n.kind)
                         ^
make: *** [pmgen] Error 1
Traceback (most recent call last):
  File "nim-pymod/pmgen.py", line 525, in <module>
    main()
  File "nim-pymod/pmgen.py", line 161, in main
    pmgen_fnames = generate_pmgen_files(nim_modfiles, pminc_basename)
  File "nim-pymod/pmgen.py", line 334, in generate_pmgen_files
    subprocess.check_call(make_command)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.pmgen-inner_loop', 'pmgen']' returned non-zero exit status 2
```

Here's the nim code:

```nimrod
...

proc lengths*(n: int): seq[int] {.exportpy.} =
  docstring"""
  Calculate the collatz path lengths for all integers up to n.
  """
  newSeq(result, n)

  var i = 1
  while i <= n:
    result[i-1] = collatz(n)
    i += 1


initPyModule("fast_inner_loop", lengths)
```

**Comment by subsetpark** [comment]
Ah, I didn't realize that sequence return types were not yet supported.
